SELECT CLIENT.NAME, COUNT(CLIENT_ID)
FROM PROJECT
INNER JOIN CLIENT
ON CLIENT.ID = PROJECT.CLIENT_ID 
GROUP BY CLIENT_ID 
HAVING COUNT(CLIENT_ID) IN (
SELECT COUNT(CLIENT_ID)
FROM PROJECT
GROUP BY CLIENT_ID
ORDER BY COUNT(CLIENT_ID) DESC
LIMIT 1
);