CREATE TABLE worker(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(1000) NOT NULL,
	BIRTHDAY DATE,
	LEVEL ENUM('Trainee','Junior','Middle','Senior') NOT NULL,
	SALARY INT,
		CHECK(LENGTH(NAME)>1),
		CHECK(BIRTHDAY>'1900-12-31'),
		CHECK(SALARY BETWEEN 100 AND 100000)
);

CREATE TABLE client(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(1000) NOT NULL,
		CHECK(LENGTH(NAME)>1)
);

CREATE TABLE project(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CLIENT_ID INT,
	START_DATE DATE,
	FINISH_DATE DATE);
ALTER TABLE project
    ADD FOREIGN KEY (CLIENT_ID) 
		REFERENCES client(ID);
		
CREATE TABLE project_worker(
PROJECT_ID INT,
WORKER_ID INT,
PRIMARY KEY (PROJECT_ID, WORKER_ID)
);
ALTER TABLE project_worker
    ADD FOREIGN KEY (PROJECT_ID) 
		REFERENCES project(ID);
ALTER TABLE project_worker
    ADD FOREIGN KEY (WORKER_ID) 
		REFERENCES worker(ID);