SELECT
CONCAT ('Project  ', PROJECT.ID)
AS NAME,
DATEDIFF(month, PROJECT.START_DATE, PROJECT.FINISH_DATE)
* WORKER.SALARY
AS PRICE
FROM PROJECT 
INNER JOIN PROJECT_WORKER
ON PROJECT_WORKER.PROJECT_ID = PROJECT.ID
INNER JOIN WORKER
ON WORKER.ID = PROJECT_WORKER.WORKER_ID 